### ISSUE TITLE
pipe.h code example segfaults

### ISSUE THREAD

**Issue by noporpoise** [cgaebel/pipe#3]
The code example in pipe.h seqfaults:

```
#include <stdlib.h>
#include <stdio.h>
#include "pipe.h"

#define THREADS 4

int main()
{
  pipe_t* p = pipe_new(sizeof(int), 0);
  pipe_producer_t* pros[THREADS] = { pipe_producer_new(p) };
  pipe_consumer_t* cons[THREADS] = { pipe_consumer_new(p) };
  pipe_free(p);
  // At this point, you can freely use the producer and consumer handles.
  // Then clean them up when you're done!
  for(int i = 0; i < THREADS; ++i) {
    pipe_producer_free(pros[i]);
    pipe_consumer_free(cons[i]);
  }
}
```

on a mac (10.9) compiled with:

```
    gcc -Wall -Wextra -std=c99 -O2 -o ptest -I pipe/ ptest.c pipe/pipe.o
```

Am I doing something stupid?

**Comment by joshring** [comment]
Could it be the `-std=c99` part?

**Comment by p0wl90** [comment]
I'm fairly new to C but doesn't this code spawn one producer and one consumer and tries to free 4? At least, the following code works: 
``int main() {
    pipe_t* p = pipe_new(sizeof(int), 0);
    pipe_producer_t* pros[THREADS];
    pipe_consumer_t* cons[THREADS];
    for (int i = 0; i < THREADS; ++i) {
        pros[i] = pipe_producer_new(p);
        cons[i] = pipe_consumer_new(p);
    }
    pipe_free(p);

    // At this point, you can freely use the producer and consumer handles.
    // Then clean them up when you're done!

    for (int i = 0; i < THREADS; ++i) {
        pipe_producer_free(pros[i]);
        pipe_consumer_free(cons[i]);
    }
}``
