### ISSUE TITLE
check_invariants: Assertion `((s.begin) >= (s.buffer) && (s.begin) <= (s.bufend))' failed

### ISSUE THREAD

**Issue by soon** [cgaebel/pipe#4]
There is a situation, when `s.begin` becomes invalid. Let assume the following scenario:

1. `s.buffer = 0x360e0`, `s.bufend = 0x362ec`, `elem_size = 0xc`
2. In the `pop_without_locking` function, `first_bytes_to_copy` is `8`, so, `bytes_to_copy > 0`.
3. `s.begin = 0x362e0`
4. After `s.begin += elem_size;` it becomes `0x362ec` (`s.bufend`)
5. After `s.begin = wrap_ptr_if_necessary(s.buffer, s.begin, s.bufend);` it becomes `0x360e0` (`s.buffer`)
6. After `s.begin += bytes_to_copy;` it becomes `0x360e4`
7. After `s.begin -= elem_size;` it becomes `0x360d8` and goes out of `s.buffer` bound, because it was wrapped before.

Steps to reproduce:

1. Invoke `wrap` situation
2. Read **some** (not zero!) bytes from the end
3. Wait until it `assert`s

I am sorry for the issue without testcase, but I will write it (and a solution, if lucky) as soon as possible. 

Could you, please, add a fix? Thanks!

**Comment by cgaebel** [comment]
Thanks a ton for the bug report!

I'll take a close look at the issue this weekend. If you have a test case + patch written by the time I start looking at this, I'll be sure to get it merged. If not, no worries. I'll take care of it.

**Comment by soon** [comment]
I have added a test case draft: https://github.com/soon/pipe/commit/1b188df9697cfc81176c334cb290aa6d94aeb33c and a sample log output: https://github.com/soon/pipe/commit/b45da56360b3292cd37491d6a5b28aad43943966 (because I am not sure, if this fail on your machine); Please, tell me if you need more information.

**Comment by cgaebel** [comment]
I have added your test case, and written a fix. Please confirm!

**Comment by soon** [comment]
Thank you a lot! I will test it again in the next week.
